# Look docs here https://github.com/asottile/pyupgrade/blob/main/README.md
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: pretty-format-json
      - id: trailing-whitespace

  # An extremely fast Python linter, written in Rust
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    # Ruff version.
    rev: v0.0.290
    hooks:
      - id: ruff
        args:  [--fix, --exit-non-zero-on-fix]

  # Flake8 is a wrapper around these tools:
  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        additional_dependencies: ["wemake-python-styleguide"]

  # Pyupgrade is a tool (and pre-commit hook) to automatically upgrade syntax for newer versions of the language
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.11.0
    hooks:
      - id: pyupgrade
        args: [--py310-plus]

  # isort your imports, so you don't have to.
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort

  # Mypy is a static type checker for Python
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
      - id: mypy
