fix = true
line-length = 80

[lint]
select = ['ALL']
ignore = [
    'CPY', 'FURB', 'LOG',  # preview hooks
    'FA', 'D203', 'D212', 'D213', 'COM812', 'ISC001',  # conflicting rules
    # our preferences
    'D407', 'D415',
]

[format]
# Following standard Python guidelines, use single quotes for strings.
#quote-style = 'single'

[flake8-quotes]
#inline-quotes = 'single'
